/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CompilerOutput {
  code: string
  map: string
}

export declare class TemplateCompiler {
  constructor(options?: CompilerOptions | undefined | null)
  compileModule(sourceText: string, moduleType: string): Promise<CompilerOutput>
  renderStart(): void
  compileChunk(sourceText: string): Promise<CompilerOutput>
}

export interface CompilerOptions {
  dedupeStrings?: boolean
  oveo?: boolean
}
