window.__snapshot__ = {
  "<div> 0": "\n<div />\n",
  "'abc' 0": "\nabc\n",
  "<span> 0": "\n<span />\n",
  "<div> (null props) 0": "\n<div />\n",
  "<div> ({} props) 0": "\n<div />\n",
  "<div tabIndex='1'> 0": "\n<div\n  tabIndex=\"1\"\n/>\n",
  "<div tabIndex='1' title='2'> 0": "\n<div\n  tabIndex=\"1\"\n  title=\"2\"\n/>\n",
  "<div data-abc='a' 0": "\n<div\n  data-abc=\"a\"\n/>\n",
  "<div aria-type='button' 0": "\n<div\n  aria-type=\"button\"\n/>\n",
  "<div class=null> 0": "\n<div />\n",
  "<div class=''> 0": "\n<div\n  class=\"\"\n/>\n",
  "<div class='a'> 0": "\n<div\n  class=\"a\"\n/>\n",
  "<div class='a b'> 0": "\n<div\n  class=\"a b\"\n/>\n",
  "<div style=null> 0": "\n<div />\n",
  "<div style={top: 10px}> 0": "\n<div  style={\n    top: 10px;\n  }\n/>\n",
  "<div style={float: 'left'}> 0": "\n<div  style={\n    float: left;\n  }\n/>\n",
  "<div style={top: 10px; left: 20px}> 0": "\n<div  style={\n    top: 10px;\n    left: 20px;\n  }\n/>\n",
  "<div></div> (null children) 0": "\n<div />\n",
  "<div>'abc'</div> 0": "\n<div >\n  abc\n</div>\n",
  "<div>10</div> 0": "\n<div >\n  10\n</div>\n",
  "<div><span></div> 0": "\n<div >\n  <span />\n</div>\n",
  "<div>[]</div> 0": "\n<div />\n",
  "<div>[<span>]</div> 0": "\n<div >\n  <span />\n</div>\n",
  "<div>[<span>, <strong>]</div> 0": "\n<div >\n  <span />\n  <strong />\n</div>\n",
  "<div>[  <div>'hello'</div>,  <div>[<span>'world'</span>, <div><span></div>]</div>,  <div><div></div>,  <div>]</div> 0": "\n<div >\n  <div >\n    hello\n  </div>\n  <div >\n    <span >\n      world\n    </span>\n    <div >\n      <span />\n    </div>\n  </div>\n  <div >\n    <div />\n  </div>\n  <div />\n</div>\n",
  "<circle> 0": "\n<circle />\n",
  "<circle class='a'> 0": "\n<circle\n  class=\"a\"\n/>\n",
  "<circle style={top: 10px}> 0": "\n<circle  style={\n    top: 10px;\n  }\n/>\n",
  "<circle xlink:href='a'> 0": "\n<circle\n  xlink:href=\"a\"\n/>\n",
  "<circle xml:text='a'> 0": "\n<circle\n  xml:test=\"a\"\n/>\n",
  "<input type='text'> 0": "\n<input\n  type=\"text\"\n/>\n",
  "<input type='text' value='abc'> 0": "\n<input\n  type=\"text\"  value=\"abc\"\n/>\n",
  "<input type='checkbox'> 0": "\n<input\n  type=\"checkbox\"\n/>\n",
  "<input type='checkbox' checked='true'> 0": "\n<input\n  type=\"checkbox\"  checked=\"true\"\n/>\n",
  "<textarea> 0": "\n<textarea />\n",
  "<audio> 0": "\n<audio />\n",
  "<audio volume=0.5> 0": "\n<audio\n  volume=\"0.5\"\n/>\n",
  "<video volume=0.5> 0": "\n<video\n  volume=\"0.5\"\n/>\n",
  "<textarea>abc</textarea> 0": "\n<textarea >\n  abc\n</textarea>\n"
};
