name: CI
env:
  ACTION_CACHE_PATH: |
    ~/.bun/install/cache
    node_modules/
permissions:
  contents: write
  id-token: write
on:
  workflow_dispatch:
    inputs:
      publish:
        required: false
        type: boolean
  push:
    paths:
      - packages/**
      - bun.lock
      - "!crates/**"
      - "!packages/@ivi/compiler/**"
      - "!tests/compiler/**"
    branches:
      - master
  pull_request:
    paths:
      - packages/**
      - bun.lock
      - "!crates/**"
      - "!packages/@ivi/compiler/**"
      - "!tests/compiler/**"
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  publish:
    name: Publish
    if: "${{ github.event_name != 'pull_request' && (inputs.publish || startsWith(github.event.head_commit.message, 'publish:')) }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: oven-sh/setup-bun@v2
      - uses: extractions/setup-just@v3
      - uses: actions/cache@v4
        with:
          path: ${{ env.ACTION_CACHE_PATH }}
          key: CI
      - run: just init
      - run: just tsc
      - name: Publish to NPM
        run: |
          npm config set provenance true
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          just publish --provenance --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
