name: CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun test
        env:
          CI: true

