name: CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "pnpm"
      - run: make init
      - run: make build
      - run: make test
        env:
          CI: true
