name: CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
        env:
          CI: true
          COVERAGE: true
